name: const_math
description: A package providing compile time math functions, not optimized for run time calculation.
version: 1.0.1
repository: https://github.com/kirara-shiroyoru/const_math

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
